CREATE TABLE poses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    motor1 INT NOT NULL CHECK (motor1 BETWEEN 0 AND 180),
    motor2 INT NOT NULL CHECK (motor2 BETWEEN 0 AND 180),
    motor3 INT NOT NULL CHECK (motor3 BETWEEN 0 AND 180),
    motor4 INT NOT NULL CHECK (motor4 BETWEEN 0 AND 180),
    motor5 INT NOT NULL CHECK (motor5 BETWEEN 0 AND 180),
    motor6 INT NOT NULL CHECK (motor6 BETWEEN 0 AND 180),
    status TINYINT DEFAULT 1 CHECK (status IN (0, 1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
